name: 'Build process'

on:
  workflow_dispatch:
  release:
    types:
    - created
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start time
      run: |
        date
    - name: Extract branch name
      run: echo "branch=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
      id: extract_branch
    - name: Print branch name
      run: echo ${{ steps.extract_branch.outputs.branch }}
    - name: Extract out the branch name from tag
      run: |
        echo "branch_name=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
        echo "tag_name=${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
    - name: Show the tag
      run: |
        echo $tag_name
    - name: Show the extract branch
      run: |
        echo $branch_name
    - name: Extract branch name 2
      run: |
        echo "branch_name2=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        echo "tag_name2=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
    - name: Show the tag 2
      run: |
        echo $tag_name2
    - name: Show the extract branch 2
      run: |
        echo $branch_name2
    - name: Show github repository
      run: |
        echo ${GITHUB_REPOSITORY#*/}
    - name: Checkout
      uses: actions/checkout@v3
    - name: Java setup
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
    - name: Java build binaries
      run: ./gradlew clean build -x test --no-daemon
    - name: Completion time
      run: |
        date
